### ISSUE TITLE
On bosses only uses 1 sword with nothing in the other hand

### ISSUE THREAD

**Issue by Ikkoru** [livercat/scribble#1]
Also tried setting one default sword, but it didn't help.

Settings:

`var elemental_items = [`
`  ["wand", `
`    ["fire", "D"],`
`    ["poison", "D"],`
`  ],`
`  ["sword", `
`    ["aether", "D"],`
`    ["fire", "D"],`
`    ["ice", "D"],`
`    ["poison", "D"],`
`    ["vigor", "D"],`
`  ],`
`  ["shield", `
`    ["vigor", "ah"],`
`    ["default", "compound shield"],`
`  ],`
`]`

`var special_items = [`
`  "dashing", "bardiche", "heavy hammer",`
`]`

`var lost_items = [`
`  "blade", "arm", "mask"`
`]`

`var evade_shield = "vigor ah"`

`var armor_shield = "compound shield"`

`var melee_aoe_weapon = "bardiche"`

`var ranged_aoe_weapon = "wands"`

`var ranged_st_weapon = "wands"`

`/*********************`
`**     #Settings    **`
`*********************/`
`var ui_show_cd = false`

`var ui_show_statuses = false`

`var ui_show_debug = false`

`var aoe_treshold = 3`

`var low_hp_threshold = 0.5`

`var use_shield_on_low_hp = true`

`var prefer_ranged = false`

`var max_chill = 6`

`var bfg_quest = "variety"`

`var bfg_defeated_foes = [`
`  "Ant", "Ant Hill", "Big A** Snail", "Big Booo",`
`  "Bolesh", "Booo", "Cult Guard", "Dominotaur",`
`  "Perfected", "Bearer of Stones",`
`  "Elite Ice elemental", "Fire Elemental",`
`  "Ground Serpent", "Huge Mosquito",`
`  "Huge Snail", "Ki Gobbler", "Ki Slurper",`
`  "Knee Chopper", "Mine Walker", "Nail Biter",`
`  "Neck Warmer", "Not Caviar", "Poison Adept",`
`  "R.I.P.", "Serpent Handler", "Skeletimmy",`
`  "Skeletony", "Skin Peeler", "Stone Scarab",`
`  "Toupée Snatcher", "Whip Controller",`
`  "Worm Rider", "Wound Licker"`
`]`

`var smite_damage = 85`

`var smite_treshold = 7`

`var pickpocket_quest = true`

`var arm_damage = 20`
`var max_pickpocket = 1`

`var maintain_pickpocket = false`

`var mask_quest = false`

**Comment by livercat** [comment]
Thank you for the report! I've just released version 1.3 that has a lot of bugfixes and improvements for weapon switching, please try it out :)
I'll close this issue for the time being, please create a new one if you continue to have issues with it.
